<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Program Attendants - {{ $program->title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .program-info { margin-bottom: 20px; }
        .summary { background: #f8f9fa; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f2f2f2; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; }
        .badge-success { background: #28a745; color: white; }
        .badge-warning { background: #ffc107; color: black; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Program Attendance Report</h1>
        <h2>{{ $program->title }}</h2>
    </div>

    <div class="program-info">
        <p><strong>Date:</strong> {{ $program->start_date->format('F j, Y \a\t h:i A') }} - {{ $program->end_date->format('h:i A') }}</p>
        <p><strong>Venue:</strong> {{ $program->venue }}</p>
        <p><strong>Report Generated:</strong> {{ $exportDate->format('F j, Y \a\t h:i A') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p><strong>Total Confirmed Registrations:</strong> {{ $registrations->count() }}</p>
        <p><strong>Total Attended:</strong> {{ $attendedCount }}</p>
        <p><strong>Attendance Rate:</strong> {{ $registrations->count() > 0 ? round(($attendedCount / $registrations->count()) * 100, 1) : 0 }}%</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Invitation Code</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($registrations as $index => $registration)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $registration->registrant_name }}</td>
                <td>{{ $registration->registrant_email }}</td>
                <td>{{ $registration->registrant_phone }}</td>
                <td><strong>{{ $registration->invitation_code }}</strong></td>
                <td>
                    @if($registration->status === 'attended')
                        <span class="badge badge-success">ATTENDED</span>
                    @else
                        <span class="badge badge-warning">REGISTERED</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($registrations->count() === 0)
    <div style="text-align: center; padding: 40px; color: #666;">
        <p>No confirmed registrations for this program.</p>
    </div>
    @endif

    <div class="footer">
        <p>Generated by YUREI System - {{ config('app.name') }}</p>
    </div>
</body>
</html>